version: '3.3'

services:

#Personnel de WoodyToys
  hangar:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils curl && sleep infinity"
    container_name: hangar
    volumes:
      - ./intranet/resolv.conf:/etc/resolv.conf
    networks:
      usr_network:
        ipv4_address: 10.0.0.2
    
  atelier:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils && sleep infinity"
    container_name: atelier
    networks:
      usr_network:
        ipv4_address: 10.0.0.3

  secretariat:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils && sleep infinity"
    container_name: secretariat
    networks:
      usr_network:
        ipv4_address: 10.0.0.4

  direction:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils && sleep infinity"
    container_name: direction
    networks:
      usr_network:
        ipv4_address: 10.0.0.5

  comptabilite:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils && sleep infinity"
    container_name: comptabilite
    networks:
      usr_network:
        ipv4_address: 10.0.0.6

  commerciaux:
    image: ubuntu
    command: bash -c "apt-get update && apt-get install -y iputils-ping dnsutils && sleep infinity"
    container_name: commerciaux
    networks:
      usr_network:
        ipv4_address: 10.0.0.7

#serveur web
  web:
    image: php:7.2-apache
    expose:
      - 80
    command: bash -c "service apache2 start && sleep infinity"
    container_name: web
    volumes:
      - ./DMZ/WEB/sites/:/var/www
      - ./DMZ/WEB/intranet.conf:/etc/apache2/sites-available/intranet.conf
    networks:
      usr_network:
        ipv4_address: 10.0.0.9
  
  #db:
  #image: mysql:latest
  #expose:
  #-3306
  #environement
  #volume
  #network
  #container-name

#Resolver(DNS)

  Resolver:
    image: ubuntu/bind9
    expose:
      - 53/udp
      - 53/tcp
    command: named -g #lance bind
    container_name: Resolver
    networks:
      usr_network:
        ipv4_address: 10.0.0.8
    volumes:
      - ./intranet/named.conf:/etc/bind/named.conf
      - ./intranet/woodytoys.lab.zone:/etc/bind/woodytoys.lab.zone


#Network

networks:
  usr_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24