version: '3.8'

services:

  b2b:
    build: ./b2b
    container_name: b2b
    ports:
      - "8080:80"
    networks:
      woodytoys:
        ipv4_address:  10.0.0.2

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: psw
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: user
      MYSQL_PASSWORD: psw
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      woodytoys:
        ipv4_address:  10.0.0.3

  userdav:
    build: ./user
    container_name: userdav
    networks:
      woodytoys:
        ipv4_address:  10.0.0.4

  resolver:
    build: ./resolver
    container_name: resolver
    depends_on:
      - soa
    networks:
      woodytoys:
        ipv4_address:  10.0.0.5
  

  soa:
    build: ./soa
    container_name: soa
    networks:
      woodytoys:
        ipv4_address:  10.0.0.6
  
  web:
    build: ./webVitrine
    container_name: webvitrine
    ports:
      - "80:80"
    networks:
      woodytoys:
        ipv4_address:  10.0.0.7

  mail:
    build: ./mail
    container_name: mail
    networks:
      woodytoys:
        ipv4_address: 10.0.0.8
        
  userthomas:
    build: ./user
    container_name: userthomas
    networks:
      woodytoys:
        ipv4_address:  10.0.0.9
        
  intranet:
    build: ./intranet
    container_name: intranet
    networks:
      woodytoys:
        ipv4_address: 10.0.0.10

networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

volumes:
  mysql-data:
