version: '3.8'

services:

  db:
    image: mysql
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: psw
      MYSQL_DATABASE: woodytoys
      MYSQL_USER: user
      MYSQL_PASSWORD: psw
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      woodytoys:
        ipv4_address:  10.0.0.3

  userdav:
    build: ./user
    container_name: userdav
    networks:
      woodytoys:
        ipv4_address:  10.0.0.4

  resolver:
    build: ./resolver
    container_name: resolver
    depends_on:
      - soa
    networks:
      woodytoys:
        ipv4_address:  10.0.0.5
  

  soa:
    build: ./soa
    container_name: soa
    networks:
      woodytoys:
        ipv4_address:  10.0.0.6

  mail:
    build: ./mail
    container_name: mail
    networks:
      woodytoys:
        ipv4_address: 10.0.0.8
        
  userthomas:
    build: ./user
    container_name: userthomas
    networks:
      woodytoys:
        ipv4_address:  10.0.0.9
  intranet:
    build: ./intranet
    container_name: intranet
    networks:
      woodytoys:
        ipv4_address: 10.0.0.10
  
  webpub:
    build: ./webPub
    container_name: webpub
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      woodytoys:
        ipv4_address: 10.0.0.11
    volumes:
      - /etc/ssl/private:/etc/ssl/private
    
  soa_externe:
    build: ./soa_externe
    container_name: soa_externe
    ports:
      - "172.16.1.4:53:53/tcp"
      - "172.16.1.4:53:53/udp"
    networks:
      woodytoys:
        ipv4_address: 10.0.0.12

networks:
  woodytoys:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

volumes:
  mysql-data:
